### ISSUE TITLE
Unable to fetch data through cyanite http services

### ISSUE THREAD

**Issue by vamsikorada** [pyr/cyanite#210] opened 2016-06-09 18:57 UTC
I setted up cassandra and ran the cynanite jar. I was able to push data to cassandra, and the http service ping is giving the correct response. However, when i tries to use the cyanite http service "paths" (http://localhost:8090/paths?query=*), i am getting the following error message as response `{"message":"No matching method found: substring for class io.cyanite.index$segmentize"}`

Here is the stacktrace of the error

```
ERROR [2016-06-10 00:19:47,110] nioEventLoopGroup-3-1 - io.cyanite.api could not process request
java.lang.IllegalArgumentException: No matching method found: substring for class io.cyanite.index$segmentize
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[cyanite-0.5.1-standalone.jar:na]
	at globber.glob$filter_compound_partition.invokeStatic(glob.clj:272) ~[cyanite-0.5.1-standalone.jar:na]
	at globber.glob$filter_compound_partition.invoke(glob.clj:266) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$partial$fn__4759.invoke(core.clj:2515) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$map$fn__4785.invoke(core.clj:2646) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RT.seq(RT.java:521) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$seq__4357.invokeStatic(core.clj:137) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:641) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$mapcat.invokeStatic(core.clj:2674) ~[cyanite-0.5.1-standalone.jar:na]
	at globber.glob$filter_compound_ast.invokeStatic(glob.clj:313) ~[cyanite-0.5.1-standalone.jar:na]
	at globber.glob$glob.invokeStatic(glob.clj:355) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index$matches$iter__4447__4451$fn__4452$fn__4453.invoke(index.clj:71) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index$matches$iter__4447__4451$fn__4452.invoke(index.clj:71) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.RT.seq(RT.java:521) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$seq__4357.invokeStatic(core.clj:137) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6545) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index$matches.invokeStatic(index.clj:71) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.index.AgentIndex.prefixes(index.clj:107) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$fn__7338.invokeStatic(api.clj:115) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$fn__7338.invoke(api.clj:109) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.MultiFn.invoke(MultiFn.java:229) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$process.invokeStatic(api.clj:89) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.api$make_handler$fn__7360.invoke(api.clj:153) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.http$request_handler$fn__7081.invoke(http.clj:110) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.http$netty_handler$fn__7089.invoke(http.clj:125) [cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.http.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite-0.5.1-standalone.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

```

And here is my cyanite.yaml

```
logging:
  level: info
  console: true
  files:
    - "/opt/cyanite/cyanite.log"
input:
  - type: "carbon"
    host: "localhost"
    port: 2003
index:
  - type: cassandra
    options:
      cluster: "localhost"
      keyspace: "metric"
store:
  cluster: "localhost"
  keyspace: "metric"
api:
  port: 8090
engine:
  rules:
    default:
      - "5s:1h"
```

Is this a bug or am i doing anything wrong?

**Comment by ifesdjeen** [comment] 2016-06-10 16:12
I can't reproduce this on the last master. I get the paths returned. 

From what I can say this is some outdated version as AgentIndex is used.

**Comment by zbintliff** [comment] 2016-07-06 21:28
I am seeing the same issue.  Using the latest commit off of master.  I have tried with multiple Cassandra 2.1.X versions (10-14).  Connecting to Cassandra directly I am getting the metrics I am putting in there but I am unable to query because of this error.

**Comment by zbintliff** [comment] 2016-07-06 21:29
I also have AgentIndex setup since we are trying to POC this and not include the Cassandra Index.

**Comment by ifesdjeen** [comment] 2016-07-07 07:33
@zbintliff could you post an entire stacktrace and query? I'll check it again. Last time I had no success reproducing it.

**Comment by zbintliff** [comment] 2016-07-07 13:49
I was getting the error when running a simple wildcard query `curl localhost:8080/paths?query=*`.  

I was able to resolve it by using the schema referenced [here](https://github.com/pyr/cyanite/blob/master/doc/schema.cql) and not on cyanite.io.  After updating the schema, I then switched to a Cassandra agent and I was able to query the paths no problem.

The stack trace I received is the exact same as posted earlier in this thread.

**Comment by ifesdjeen** [comment] 2016-07-07 14:23
Yes, AgentIndex will be deprecated shortly. Also, documentation website is outdated while we were preparing for the release...

**Comment by zbintliff** [comment] 2016-07-07 14:32
Ok, thanks for the info.  We are currently trying to POC Cyanite vs KairosDB as a Graphite replacement.  Do you have a commit hash we should work off of?  Also, any ETA on the release so we can POC on known stable point?

(You can reclose this ticket then)

**Comment by ifesdjeen** [comment] 2016-07-07 15:11
I'm afraid I can't really give any estimates, as the both maintainers are full-time employed at the moment and we do it in our spare time. Recent weeks have been a bit rough in that regard. If the current outstanding PR gets merged, we'll release the first alpha GA.

**Comment by ifesdjeen** [comment] 2016-07-07 16:56
I'm closing then, if this is a documentation issue - we'll have to rework current docs alltogether

**Comment by Mortinke** [comment] 2016-08-16 06:32
I am seeing the same issue with the latest [master](https://github.com/pyr/cyanite/commit/a255439eaeeebb8bc5dfe5506a4bcb56f22bfb1c) and cassandra 2.1.10 ([cqlsh 5.0.1 | Cassandra 2.1.10 | CQL spec 3.2.1 | Native protocol v3]). 

The last version which works with cassandra 2.1.x that i found was the [commit](https://github.com/pyr/cyanite/tree/0b855b24acc7e9de85d0c6d3f3692183c03ea926). 

In my opinion, many users use currently cassandra 2.1.x [see](https://twitter.com/PatrickMcFadin/status/758361307644964864). So it would be nice, that we could support a version that works with it.

**Comment by ifesdjeen** [comment] 2016-08-16 06:52
Cyanite only works with Cassandra `3.4` and upwards because of the custom indexes we're using.

**Closed** 2016-08-16 06:55 UTC
