### ISSUE TITLE
Failure to write any metrics

### ISSUE THREAD

**Issue by stuartbfox** [pyr/cyanite#190] opened 2016-02-12 08:12 UTC
Im running the latest commit and Im seeing 0 writes to Cassandra. Ive got it running in debug mode to see whats going in and I get this shortly after startup.

```
`DEBUG [2016-02-12 08:06:01,689] epollEventLoopGroup-3-1 - io.cyanite.api got request:  {:uri "/", :get-params {}, :body-params nil, :params {}, :request-method :get, :version "HTTP/1.1", :headers {:user-agent "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2", :host "10.29.97.19:8080", :accept "*/*", :content-length "0"}, :body ""}
WARN [2016-02-12 08:06:02,034] pool-1-thread-1 - io.cyanite uncaught exception
java.lang.RuntimeException: java.lang.IllegalArgumentException: No implementation of method: :metric-matches? of protocol: #'io.cyanite.engine.rule/MetricMatcher found for class: clojure.lang.MapEntry
	at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45) ~[cyanite-0.5.1-standalone.jar:na]
	at com.lmax.disruptor.dsl.ExceptionHandlerWrapper.handleEventException(ExceptionHandlerWrapper.java:18) ~[cyanite-0.5.1-standalone.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:148) ~[cyanite-0.5.1-standalone.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: No implementation of method: :metric-matches? of protocol: #'io.cyanite.engine.rule/MetricMatcher found for class: clojure.lang.MapEntry
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$fn__707$G__702__714.invoke(rule.clj:54) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$__GT_exec_plan$fn__742.invoke(rule.clj:66) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$some.invokeStatic(core.clj:2592) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.rule$__GT_exec_plan.invokeStatic(rule.clj:64) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$make_resolutions.invokeStatic(engine.clj:59) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fetch_resolutions.invokeStatic(engine.clj:67) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.Engine.ingest_BANG_(engine.clj:94) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fn__3957$G__3953__3960.invoke(engine.clj:18) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$fn__3957$G__3952__3964.invoke(engine.clj:18) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.core$partial$fn__4759.invoke(core.clj:2515) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue.DisruptorQueue$fn__3662.invoke(queue.clj:75) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$event_handler$reify__3642.onEvent(queue.clj:49) ~[cyanite-0.5.1-standalone.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) ~[cyanite-0.5.1-standalone.jar:na]
	... 3 common frames omitted
INFO [2016-02-12 08:06:03,965] cyanite-snapshot - io.cyanite.engine.writer starting snapshot.
DEBUG [2016-02-12 08:06:11,702] epollEventLoopGroup-3-1 - io.netty.handler.logging.LoggingHandler [id: 0x96a2eb22, /10.29.97.19:8080] RECEIVED: [id: 0x5112d8cb, /10.29.97.19:13490 => /10.29.97.19:8080]
DEBUG [2016-02-12 08:06:11,704] epollEventLoopGroup-3-1 - io.cyanite.api got request:  {:uri "/", :get-params {}, :body-params nil, :params {}, :request-method :get, :version "HTTP/1.1", :headers {:user-agent "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2", :host "10.29.97.19:8080", :accept "*/*", :content-length "0"}, :body ""}
INFO [2016-02-12 08:06:13,973] cyanite-snapshot - io.cyanite.engine.writer starting snapshot.
DEBUG [2016-02-12 08:06:21,715] epollEventLoopGroup-3-1 - io.netty.handler.logging.LoggingHandler [id: 0x96a2eb22, /10.29.97.19:8080] RECEIVED: [id: 0x29d5630e, /10.29.97.19:13496 => /10.29.97.19:8080]
DEBUG [2016-02-12 08:06:21,716] epollEventLoopGroup-3-1 - io.cyanite.api got request:  {:uri "/", :get-params {}, :body-params nil, :params {}, :request-method :get, :version "HTTP/1.1", :headers {:user-agent "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2", :host "10.29.97.19:8080", :accept "*/*", :content-length "0"}, :body ""}`
```
Anything else I can provide to help diagnose?

BR
Stuart

**Comment by ifesdjeen** [comment] 2016-02-12 08:14
Thanks for giving Cyanite a try and reporting that one! Sorry you hit that issue.
This was a result of recent refactoring and is already addressed in #185. Also, duplicate of #189. 

We are working very hard to make the release available within the next several weeks. We are in the process of stabilizing and removing performance bottlenecks at the moment.

**Closed by ifesdjeen** 2016-02-12 08:14 UTC
