### ISSUE TITLE
Rollups and inserts

### ISSUE THREAD

**Issue by chjohnst** [pyr/cyanite#65] opened 2014-10-08 18:14 UTC
If I have a rollup value of 10s, but insert data into Cassandra in 1s increments I noticed the data field is an array where I am actually inserting 10 records into the one rollup.  Is this expected?  Looking at the code it is, but was this a way of handling more of a statsd approach in cyanite?

**Comment by pyr** [comment] 2015-07-23 13:18
duplicate of #46

**Closed by pyr** 2015-07-23 13:18 UTC
