### ISSUE TITLE
io.netty.channel.DefaultChannelPipeline An exceptionCaught()

### ISSUE THREAD

**Issue by jippi** [pyr/cyanite#131] opened 2015-09-22 10:11 UTC
With latest `master` HEAD commit

````
logging:
  level: info
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"

inputs:
  - type: "carbon"
    host: "127.0.0.1"
    port: 2003

store:
  type: "cassandra-v2"
  cluster: "cassandra.service.bownty"
  keyspace: "metric"

index: "memory"

api:
  host: "0.0.0.0"
  port: 8081

engine:
  rules:
    default:
      - "1m:90d"
      - "5m:1y"
      - "15m:10y"
```

startup log
```
-> java -jar target/cyanite-0.5.1-standalone.jar -f /etc/cyanite.yaml
10:12:06.766 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
10:12:06.772 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1708ms
10:12:08.205 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
10:12:08.206 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
10:12:08.208 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
10:12:08.297 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
10:12:08.300 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
10:12:08.301 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
10:12:08.302 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
10:12:08.302 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
10:12:08.307 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
10:12:08.307 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
10:12:08.307 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
10:12:08.308 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
10:12:08.309 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
10:12:08.309 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
10:12:08.309 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
10:12:08.309 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
10:12:08.309 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
starting with configuration:  /etc/cyanite.yaml
INFO [2015-09-22 10:12:08,675] main - io.cyanite installing signal handlers
INFO [2015-09-22 10:12:08,677] main - io.cyanite ready to start system
INFO [2015-09-22 10:12:08,744] main - com.datastax.driver.core.NettyUtil Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
INFO [2015-09-22 10:12:09,511] main - com.datastax.driver.core.policies.DCAwareRoundRobinPolicy Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO [2015-09-22 10:12:09,512] main - com.datastax.driver.core.Cluster New Cassandra host /195.154.134.124:9042 added
INFO [2015-09-22 10:12:09,512] main - com.datastax.driver.core.Cluster New Cassandra host cassandra.service.bownty/195.154.134.125:9042 added
INFO [2015-09-22 10:12:09,512] main - com.datastax.driver.core.Cluster New Cassandra host /195.154.134.126:9042 added
INFO [2015-09-22 10:12:09,631] main - io.cyanite.engine starting engine
INFO [2015-09-22 10:12:09,746] claypoole-2-0 - org.eclipse.jetty.server.Server jetty-9.3.z-SNAPSHOT
INFO [2015-09-22 10:12:09,775] claypoole-2-0 - org.eclipse.jetty.server.ServerConnector Started ServerConnector@3c9fa964{HTTP/1.1,[http/1.1]}{0.0.0.0:8081}
INFO [2015-09-22 10:12:09,776] claypoole-2-0 - org.eclipse.jetty.server.Server Started @4711ms

```

goes crazy with the following output first time any events are emitted

```
WARN [2015-09-22 10:10:14,954] nioEventLoopGroup-2-2 - io.netty.channel.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[na:1.8.0_60]
	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[na:1.8.0_60]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$queue_engine$reify__813.add_BANG_(queue.clj:40) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.Engine.accept_BANG_(engine.clj:54) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.carbon$pipeline$fn__9783.invoke(carbon.clj:38) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.input.carbon.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source) ~[cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) ~[cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110) [cyanite-0.5.1-standalone.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [cyanite-0.5.1-standalone.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by jippi** [comment] 2015-09-22 10:13
nothing is ever flushed to cassandra

**Comment by jippi** [comment] 2015-09-22 10:36
Now I'm seeing this

```
DEBUG [2015-09-22 10:36:05,771] claypoole-1-1 - io.cyanite.engine in write callback:  #io.cyanite.engine.buckets.MetricSnapshot{:path "statsite.gauges.production.servers.elastic03.elasticsearch.indices.kibana-int.indexing.delete_total", :time 1442917800, :mean 0.0, :max 0.0, :min 0.0, :sum 0.0, :resolution #io.cyanite.engine.rule.Resolution{:precision 300, :period 31536000}}
WARN [2015-09-22 10:36:05,771] claypoole-0-0 - io.cyanite.engine.queue could not process element on queue 0 for :ingestq
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[na:1.8.0_60]
	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[na:1.8.0_60]
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[cyanite-0.5.1-standalone.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$queue_engine$reify__813.add_BANG_(queue.clj:40) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine$ingest_at_resolution.invoke(engine.clj:26) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.Engine$fn__9675.invoke(engine.clj:38) ~[cyanite-0.5.1-standalone.jar:na]
	at io.cyanite.engine.queue$queue_engine$reify__813$future_body__814$fn__815.invoke(queue.clj:33
```

**Comment by jippi** [comment] 2015-09-22 10:57
after spending a few hours trying to get it work, I'm reverting back to the old version - seems like the refactor caused it to require excessive amount of CPU, RAM and not being able to follow a few 100k writes a minute :(

**Comment by jippi** [comment] 2015-09-22 11:27
post-frustration, I'm really grateful for the project and the time you spend maintaining it :)

**Comment by pyr** [comment] 2015-10-06 14:36
Hi @jippi, sorry for the hurdles. This is a duplicate of #121 which #134 fixed. i'm testing with 6M writes/min and have no trouble keeping up.

**Closed** 2015-10-06 14:38 UTC
